# Generated by Django 4.0.4 on 2022-05-16 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_aluno', models.CharField(max_length=100)),
                ('imagem', models.ImageField(default=None, null=True, upload_to='')),
                ('ra', models.CharField(max_length=20, unique=True)),
                ('rg', models.CharField(max_length=30, unique=True)),
                ('status', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnoEleicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_escola', models.CharField(max_length=100)),
                ('rua', models.CharField(max_length=80)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(default=None, max_length=40, null=True)),
                ('bairro', models.CharField(default=None, max_length=40, null=True)),
                ('cidade', models.CharField(default=None, max_length=40, null=True)),
                ('estado', models.CharField(default=None, max_length=40, null=True)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turma', models.CharField(max_length=20, unique=True)),
                ('nome_escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vota_escola.escola')),
            ],
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_candidatura', models.TextField()),
                ('ano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vota_escola.anoeleicao')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nome_candidato', to='vota_escola.aluno')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vota_escola.turma')),
            ],
            options={
                'unique_together': {('ano', 'candidato', 'turma')},
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='nome_escola',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='vota_escola.escola'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='turma_atual',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='vota_escola.turma'),
        ),
        migrations.CreateModel(
            name='Votos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ano_eleicao', to='vota_escola.anoeleicao')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nome', to='vota_escola.candidato')),
                ('eleitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nome_eleitor', to='vota_escola.aluno')),
            ],
            options={
                'unique_together': {('ano', 'candidato', 'eleitor')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='aluno',
            unique_together={('nome_aluno', 'ra', 'rg')},
        ),
    ]
