# Generated by Django 4.0.4 on 2022-04-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vota_escola', '0002_turma_nome_escola'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='sala',
            field=models.CharField(default=1, max_length=5),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='turma',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
