# Generated by Django 4.0.4 on 2022-04-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vota_escola', '0003_alter_candidato_sala_alter_candidato_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='sala',
            field=models.CharField(choices=[], max_length=5),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='turma',
            field=models.CharField(choices=[], max_length=20),
        ),
    ]
