# Generated by Django 4.0.4 on 2022-04-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vota_escola', '0004_alter_candidato_sala_alter_candidato_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='ra',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
