# Generated by Django 4.0.4 on 2022-04-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vota_escola', '0006_alter_aluno_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='sala',
            field=models.CharField(default=(), max_length=5),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='turma',
            field=models.CharField(default=(), max_length=20),
        ),
    ]
