# Generated by Django 4.0.4 on 2022-04-28 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vota_escola', '0008_alter_candidato_sala_alter_candidato_turma'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnoEleicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='candidato',
            name='ano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vota_escola.anoeleicao'),
        ),
        migrations.AlterField(
            model_name='eleicao',
            name='ano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ano_eleicao', to='vota_escola.anoeleicao'),
        ),
    ]
