# Generated by Django 4.0.4 on 2022-04-28 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vota_escola', '0009_anoeleicao_alter_candidato_ano_alter_eleicao_ano'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Eleicao',
            new_name='Votos',
        ),
    ]
