# Generated by Django 4.0.4 on 2022-04-28 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vota_escola', '0010_rename_eleicao_votos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vota_escola.sala'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vota_escola.turma'),
        ),
    ]
