# Generated by Django 4.0.4 on 2022-04-28 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vota_escola', '0011_alter_candidato_sala_alter_candidato_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sala_id', to='vota_escola.sala'),
        ),
    ]
