# Generated by Django 4.0.4 on 2022-05-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vota_escola', '0014_alter_aluno_nome_escola_alter_aluno_sala_atual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='password',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
